### ISSUE TITLE
'Split/JFGC.h' file not found

### ISSUE THREAD

**Issue by acoroian** [splitio/ios-client#367]
issues on 2.15 and 2.16 
works with 2.14

Getting this issues when archiving my solution.

'Split/JFGC.h' file not found

**Comment by chillaq** [comment]
Hi @acoroian, thanks for the info, checking with the team.

**Comment by javrudsky** [comment]
Hi @acoroian, Thanks for reporting the issue.
Could you provide a little bit context please? I'm trying to reproduce it without success.

**Comment by vlvs** [comment]
Had the same issue while building for tests on an external CI machine with version 2.8.0, upgrading to 2.14.0 fixed it.
```
In file included from /Users/vagrant/git/.build/SourcePackages/checkouts/ios-client/Split/Common/Utils/JFBCrypt/JFBCrypt.m:29:
/Users/vagrant/git/.build/SourcePackages/checkouts/ios-client/Split/Common/Utils/JFBCrypt/JFBCrypt.h:31:9: fatal error: 'Split/JFGC.h' file not found
```

**Comment by javrudsky** [comment]
Thank you @vls for the info. What is the package manager you're using?

**Comment by itsalan** [comment]
seeing this as well, using SPM

**Comment by vlvs** [comment]
@javrudsky I'm using SPM as well.

**Comment by javrudsky** [comment]
Hey @acoroian, @vlvs, @itsalan. Release 2.16.1 has a fix for this issue. Please let me know if we can close this issue once you update to this release.
Thanks a lot for the info guys.

**Comment by itsalan** [comment]
@javrudsky resolved for me, thanks
